spring:
  profiles:
    active: dev

  jackson:
    visibility:
      FIELD: any
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: on
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: off
      FAIL_ON_UNKNOWN_PROPERTIES: off
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: on
    default-property-inclusion: non_null

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_updates: true
        default_schema: ${POSTGRES_SCHEMA:public}
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:spring_pizza_postgres}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:spring_pizza}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    sql: debug